config/routes.rb
Stackoverflow::Application.routes.draw do
  resources :products
  resources :categories

  resources :answers

  resources :questions do
    post 'add_answer',:on=>:member
  end

  root :to => 'products#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers#,:order => 'created_at'
  validates :title,:description,:presence => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_answer
    @answer = Answer.new(params[:answer])
    @question = Question.find(params[:id])
    @question.answers << @answer
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.haml
.answer
  .description= answer.description
  .posted_on= distance_of_time_in_words_to_now(answer.created_at) + '  ago'

app/views/questions/_form.html.haml
= form_for(@question) do |f|
  - if @question.errors.any?
    #error_explanation
      %h2
        = pluralize(@question.errors.count, "error")
        prohibited this question from being saved:
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/questions/add_answer.js.erb
$("<%= escape_javascript(render 'answer',:answer=>@answer ) %>").hide().appendTo("#answers").fadeIn();
$("#answer_description").val('');
$("#answers_count").html("<%=@question.answers_count %>");

app/views/questions/edit.html.haml
%h1 Editing question
= render 'form'
= link_to 'Show', @question
|
\#{link_to 'Back', questions_path}

app/views/questions/index.html.haml
:css
  a{
      text-decoration: none;
  }

.list-header
  All Questions By Upender
#question_list
  #questions.questions
    - if @questions.blank?
      %i No Questions found....
    - else
      - @questions.each do |question|
        #question.question
          .question-content
            %a.answers{:href => "#"}
              %span.count= question.answers_count
              %span.content Answers
            %a.question-biglink{:href => question_path(question)}
              %h3.question-title
                = question.title
              %p.question-description
                %span.question-teaser
                  \—
                  \#{question.description.truncate(75)}
%br/
= link_to 'Ask New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question
= render 'form'
= link_to 'Back', questions_path

app/views/questions/show.html.haml
%h3.question_title{style: 'color: #4B7399;'}= @question.title
%hr
.question_description= @question.description
.question_answers
  %h3
    %span#answers_count
      = @question.answers_count
    Answers
  #answers
    - if @question.answers_count > 0
      -for answer in @question.answers
        = render 'answer',:answer=>answer
  %h3 Your Answer
  .your_answer
    = form_for(Answer.new,:url=> add_answer_question_path(@question),:remote=>true )do |f|
      = f.text_area :description,:cols=>94,:rows=>4
      = f.button :submit,:class=>'button primary' ,:disable_with=>'Adding..'