config/routes.rb
Stackoverflow::Application.routes.draw do
  resources :products
  resources :categories

  resources :answers

  resources :questions do
    post 'add_answer',:on=>:member
  end

  root :to => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category , :counter_cache => true
  validates :title,:description,:presence=>true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    if params[:id].present?
      @products =  Product.where(category_id: params[:id])
    else
      @products = Product.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json {
        render json: @products.as_json(root: true)
        #user.as_json(root: true)
        # => { "user": {"id": 1, "name": "Konata Izumi", "age": 16 }
      }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  -if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
.list-header Products
.categories{:align=>'center'}=link_to 'Categories',categories_path
%table
  %tr
    %th Category
    %th Title
    %th Price
    %th Description
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= product.category.name
      %td= product.title
      %td= product.price
      %td= truncate(product.description,:length=>30)
      %td= link_to 'Show', product
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @product.title
%p
  %b Price:
  = @product.price
%p
  %b Description:
  = @product.description

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path